// Stub for boot logo bitmap used by DisplayManager
// Replace with actual bitmap array generated by image2cpp or similar.
#ifndef IMAGES_H
#define IMAGES_H

const unsigned char bootLogo [] PROGMEM = {
    0x00 // <- empty bitmap
};

#endif // IMAGES_H
